### ISSUE TITLE
What appletts are you using in your top latte panel?

### ISSUE THREAD

**Issue by DylanSimowitz** [jazevedo620/dotfiles#1]
Hey, I was able to get most of your setup recreated but I'm having an issue with the top latte panel. The arch icon which I'm assuming opens some kind of plasma application launcher applet doesn't appear as well as the search icon on the left. I updated the paths of the included icons, but I think the issue might be that I don't have whatever applets you're using installed.

Thanks for sharing your setup it looks so clean.

**Comment by jazeved0** [comment]
Hey, I'm sorry for such a late response; I must not have seen your question in my inbox at the time.

Looking at the old revision of my Latte config ([link](https://github.com/jazevedo620/dotfiles/commit/6d24bfa8439ca4521a79aa0c2618e17a7ac84f2d#diff-75d6e9ff7dbd554c004c4c26de4085e4136d93ef51d031561bbd56c8a815f876R415)), it looks like it was the "Simple Menu" application menu by Sho ([KDE Store](https://store.kde.org/p/1169537/)), with a custom icon set to make it look like a search icon.

In case you see this and are still interested, I updated my dotfiles to hopefully be more polished and significantly easier to install (with much of it automated using scripts), though I'm still iterating on them a bit to clean them up and add needed documentation:

![screenshot](https://github.com/jazevedo620/dotfiles/raw/master/.github/readme/preview.png)
